"""Type declarations for the PassoFlow Rust binding."""

__version__: str

class DomBrowser:
    def __init__(self, endpoint: str) -> None: ...
    def navigate(self, url: str) -> None: ...
    def click(self, selector: str) -> None: ...
    def fill(self, selector: str, text: str) -> None: ...
    def wait_for(self, selector: str, state: str = ..., timeout_ms: int = ...) -> None: ...
    def preview_selector(self, selector: str) -> str: ...

def contract_version() -> str: ...
def normalize_yaml(yaml: str) -> str: ...
def validate_yaml(yaml: str) -> str: ...
